apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "stolon.fullname" . }}-copy-telegraf-influxdb-creds
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        app: {{ template "stolon.fullname" . }}
        release: {{ .Release.Name }}
        name: {{ template "stolon.fullname" . }}-copy-telegraf-influxdb-creds
        stolon-cluster: {{ template "stolon.clusterName" . }}
    spec:
      nodeSelector:
        gravitational.io/k8s-role: master
      restartPolicy: OnFailure
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      containers:
        - name: copy
          image: "{{ .Values.registry }}{{ .Values.telegrafImage.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.telegrafImage.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/copy-secret.sh"]
          volumeMounts:
            - name: kubectl
              mountPath: /usr/bin/kubectl
      volumes:
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
