apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stolon.fullname" . }}
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.superuser.password }}
  password: {{ .Values.superuser.password | b64enc | quote }}
  {{- else if (not .Values.superuser.forcePassword) }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  password: {{ required "A PostgreSQL superuser password required!" .Values.superuser.password }}
  {{- end }}
  {{- if .Values.replication.password }}
  pg_repl_password: {{ .Values.replication.password | b64enc | quote }}
  {{- else if (not .Values.replication.forcePassword) }}
  pg_repl_password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  pg_repl_password: {{ required "A PostgreSQL replication password required!" .Values.replication.password }}
  {{- end }}
