apiVersion: bundle.gravitational.io/v2
kind: Bundle
metadata:
  name: stolon-app
  resourceVersion: 0.0.1
  namespace: default
dependencies:
  apps:
    - gravitational.io/cluster-ssl-app:0.0.0+latest
systemOptions:
  docker:
    storageDriver: overlay
  runtime:
    version: "0.0.0+latest"
installer:
  flavors:
    prompt: "How many nodes will you need?"
    default: one
    items:
      - name: "one"
        description: "single node"
        nodes:
          - profile: node
            count: 1
      - name: "three"
        description: "three node cluster"
        nodes:
          - profile: node
            count: 3
      - name: "five"
        description: "five node cluster"
        nodes:
          - profile: node
            count: 5
      - name: "six"
        description: "five node cluster"
        nodes:
          - profile: node
            count: 3
          - profile: app
            count: 3

nodeProfiles:
  - name: node
    description: "stolon database node"
    labels:
      role: "node"
      stolon-keeper: "yes"
    requirements:
      cpu:
        min: 2
      ram:
        min: "1GB"
      volumes:
        - path: /var/lib/gravity
          capacity: "4GB"
        - name: stolon-data
          path: /var/lib/data/stolon
          targetPath: /var/lib/data/stolon
          capacity: "4GB"
          filesystems: ["ext4", "xfs"]
      network:
        minTransferRate: "1MB/s"
        ports:
          - protocol: tcp
            ranges:
              - "5431-5435"
              - "5973"
    expandPolicy: fixed-instance
    providers:
      aws:
        instanceTypes:
          - m3.large
          - m3.xlarge
          - c3.large
          - c3.xlarge
          - c3.2xlarge
          - c3.4xlarge
          - i2.xlarge
          - i2.2xlarge
  - name: app
    description: "stolon applications node"
    labels:
      role: "node"
      node-role.kubernetes.io/master: ""
    requirements:
      cpu:
        min: 2
      ram:
        min: "1GB"
      volumes:
        - path: /var/lib/gravity
          capacity: "4GB"
        - name: stolon-data
          path: /var/lib/data/stolon
          targetPath: /var/lib/data/stolon
          capacity: "4GB"
          filesystems: ["ext4", "xfs"]
      network:
        minTransferRate: "1MB/s"
        ports:
          - protocol: tcp
            ranges:
              - "5431-5435"
              - "5973"
    expandPolicy: fixed-instance
    providers:
      aws:
        instanceTypes:
          - m3.large
          - m3.xlarge
          - c3.large
          - c3.xlarge
          - c3.2xlarge
          - c3.4xlarge
          - i2.xlarge
          - i2.2xlarge

hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-install
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: stolon-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-bootstrap:latest
  postInstall:
    job: file://postInstall.yaml
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-update
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: stolon-app-update
          spec:
            hostNetwork: true
            restartPolicy: Never
            volumes:
              - name: etcdctl
                hostPath:
                  path: /usr/bin/etcdctl
              - name: varstate
                hostPath:
                  path: /var/state
            containers:
              - name: hook
                image: stolon-hook:latest
                args: ["update"]
                env:
                  - name: ETCDCTL_CA_FILE
                    value: "/var/state/root.cert"
                  - name: ETCDCTL_CERT_FILE
                    value: "/var/state/etcd.cert"
                  - name: ETCDCTL_KEY_FILE
                    value: "/var/state/etcd.key"
                  - name: ETCDCTL_PEERS
                    value: "https://127.0.0.1:2379"
                  - name: ETCD_ENDPOINTS
                    value: "127.0.0.1:2379"
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: stolon
                        key: password
                volumeMounts:
                  - name: etcdctl
                    mountPath: /usr/bin/etcdctl
                  - name: varstate
                    mountPath: /var/state
  postUpdate:
    job: file://postUpdate.yaml
  rollback:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-rollback
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: stolon-app-rollback
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: stolon-hook:latest
                args: ["rollback"]
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-uninstall
        namespace: default
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: stolon-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-uninstall:latest
