apiVersion: v1
kind: Application
metadata:
  namespace: default
  name: stolon-app
  resourceVersion: 0.0.3
base: gravitational.io/k8s-aws:1.2.3-1
hooks:
  install:
    containerImage: stolon-bootstrap:0.0.1
  uninstall:
    containerImage: stolon-uninstall:0.0.1
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
  servers:
    master:
      ram:
        min_total_mb: 2000
    node:
      cpu:
        min_count: 1
      min_count: 2
      description: "stolon server"
      labels:
        role: node
        stolon-keeper: stolon-keeper
      ram:
        min_total_mb: 2000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
          fs_types: ["xfs", "btrfs"]
      mounts:
        - source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
