---
apiVersion: v1
kind: Service
metadata:
  name: stolon-postgres
  namespace: default
  labels:
    stolon-postgres: "yes"
    product: stolon
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5434
  selector:
    stolon-proxy: "yes"
    stolon-cluster: "kube-stolon"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: stolon-keeper
  namespace: default
  labels:
    stolon-proxy: "yes"
    stolon-keeper: "yes"
    product: stolon
spec:
  selector:
    matchLabels:
      stolon-proxy: "yes"
      stolon-keeper: "yes"
  template:
    metadata:
      namespace: default
      labels:
        name: stolon-keeper
        namespace: default
        stolon-cluster: "kube-stolon"
        stolon-keeper: "yes"
        stolon-proxy: "yes"
        component: keeper
        product: stolon
    spec:
      serviceAccountName: stolon
      nodeSelector:
        stolon-keeper: "yes"
      initContainers:
        - name: fix-secrets
          image: stolon:latest
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/init-container.sh"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: etcd-secrets
              mountPath: /etc/secrets/etcd
            - name: cluster-ca
              mountPath: /etc/secrets/cluster-ca
            - name: cluster-default-ssl
              mountPath: /etc/secrets/cluster-default
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
            - name: data
              mountPath: /stolon-data
      containers:
        - name: telegraf
          image: stolon-telegraf:latest
          env:
            - name: STOLON_USERNAME
              value: "stolon"
            - name: STOLON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stolon
                  key: password
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: password
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
        - name: proxy
          image: stolon:latest
          ports:
            - containerPort: 5434
          readinessProbe:
            tcpSocket:
              port: 5434
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
          env:
            - name: PROXY
              value: "true"
            - name: STPROXY_CLUSTER_NAME
              value: "kube-stolon"
            - name: STPROXY_STORE_BACKEND
              value: "etcd"
            - name: STPROXY_STORE_CACERT
              value: "/home/stolon/secrets/etcd/root.cert"
            - name: STPROXY_STORE_CERT
              value: "/home/stolon/secrets/etcd/etcd.cert"
            - name: STPROXY_STORE_KEY
              value: "/home/stolon/secrets/etcd/etcd.key"
            - name: STPROXY_DEBUG
              value: "false"
            - name: STPROXY_PORT
              value: "5434"
            - name: STPROXY_PG_SSL_REPLICATION
              value: "true"
            - name: STPROXY_PG_SSL_CERT_FILE
              value: "/home/stolon/secrets/cluster-default/default-server.pem"
            - name: STPROXY_PG_SSL_KEY_FILE
              value: "/home/stolon/secrets/cluster-default/default-server-key.pem"
            - name: STPROXY_PG_SSL_CA_FILE
              value: "/home/stolon/secrets/cluster-ca/ca.pem"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        - name: keeper
          image: stolon:latest
          ports:
            - containerPort: 5431
            - containerPort: 5432
          volumeMounts:
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
            - name: data
              mountPath: /stolon-data
          env:
            - name: KEEPER
              value: "true"
            - name: STKEEPER_CLUSTER_NAME
              value: "kube-stolon"
            - name: STKEEPER_STORE_BACKEND
              value: "etcd"
            - name: STKEEPER_STORE_CACERT
              value: "/home/stolon/secrets/etcd/root.cert"
            - name: STKEEPER_STORE_CERT
              value: "/home/stolon/secrets/etcd/etcd.cert"
            - name: STKEEPER_STORE_KEY
              value: "/home/stolon/secrets/etcd/etcd.key"
            - name: STKEEPER_PG_REPL_USERNAME
              value: "repluser"
            - name: STKEEPER_PG_REPL_PASSWORD
              value: "replpassword"
            - name: STKEEPER_PG_SU_USERNAME
              value: "stolon"
            - name: STKEEPER_PG_SU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stolon
                  key: password
            - name: STKEEPER_DEBUG
              value: "false"
            - name: STKEEPER_PG_BIN_PATH
              value: /usr/lib/postgresql/9.6/bin
            - name: STKEEPER_PORT
              value: "5431"
            - name: STKEEPER_PG_PORT
              value: "5432"
            - name: STKEEPER_PG_SSL_REPLICATION
              value: "true"
            - name: STKEEPER_PG_SSL_CERT_FILE
              value: "/home/stolon/secrets/cluster-default/default-server.pem"
            - name: STKEEPER_PG_SSL_KEY_FILE
              value: "/home/stolon/secrets/cluster-default/default-server-key.pem"
            - name: STKEEPER_PG_SSL_CA_FILE
              value: "/home/stolon/secrets/cluster-ca/ca.pem"
            - name: STKEEPER_PG_SSL_CIPHERS
              value: >-
                ECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:
                EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:
                EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:
                EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:
                !DSS:!RC4:!SEED
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: stolon-secrets
          emptyDir: {}
        - name: data
          hostPath:
            path: /var/lib/data/stolon
        - name: etcd-secrets
          hostPath:
            path: /var/state
        - name: cluster-ca
          secret:
            secretName: cluster-ca
        - name: cluster-default-ssl
          secret:
            secretName: cluster-default-ssl
        - name: telegraf-config
          configMap:
            name: stolon-telegraf-node
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: telegraf-influxdb-creds
  namespace: default
data:
  username: dGVsZWdyYWY=
  password: c3VwZXJTZWN1cmVQYXNzd29yZA==
