---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-app-pre-update-hook
  namespace: default
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: stolon-app-pre-update-hook
    spec:
      nodeSelector:
        gravitational.io/k8s-role: master
      restartPolicy: OnFailure
      containers:
        - name: pre-update-hook
          image: stolonctl:latest
          command: ["/usr/bin/pre-update.sh"]
          env:
            - name: ETCD_CACERT
              value: "/etc/etcd/secrets/root.cert"
            - name: ETCD_CERT
              value: "/etc/etcd/secrets/etcd.cert"
            - name: ETCD_KEY
              value: "/etc/etcd/secrets/etcd.key"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_ENDPOINTS
              value: "$(NODE_NAME):2379"
          volumeMounts:
            - name: etcd-secrets
              mountPath: /etc/etcd/secrets
      volumes:
        - name: etcd-secrets
          hostPath:
            path: /var/state
