---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-app-pre-update-hook
  namespace: default
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: stolon-app-pre-update-hook
    spec:
      nodeSelector:
        gravitational.io/k8s-role: master
      restartPolicy: OnFailure
      containers:
        - name: pre-update-hook
          image: stolon-hook:latest
          command: ["/usr/local/bin/kubectl", "scale", "--replicas=0", "deployment", "stolon-sentinel"]

