---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
      - cluster-ca
      - cluster-default-ssl
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stolon
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon
    namespace: default
roleRef:
  kind: Role
  name: stolon
  apiGroup: rbac.authorization.k8s.io
