---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-sentinel
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon-sentinel
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stolon-sentinel
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon-sentinel
    namespace: default
roleRef:
  kind: Role
  name: stolon-sentinel
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-sentinel
  namespace: default
spec:
  selector:
    matchLabels:
      name: stolon-sentinel
      stolon-sentinel: "yes"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        name: stolon-sentinel
        namespace: default
        stolon-cluster: "kube-stolon"
        stolon-sentinel: "yes"
        component: sentinel
        product: stolon
    spec:
      serviceAccountName: stolon-sentinel
      securityContext:
        runAsUser: 0
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: sentinel
        image: stolon:latest
        env:
          - name: SENTINEL
            value: "true"
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcd"
          - name: STSENTINEL_STORE_CACERT
            value: "/etc/etcd/secrets/root.cert"
          - name: STSENTINEL_STORE_CERT
            value: "/etc/etcd/secrets/etcd.cert"
          - name: STSENTINEL_STORE_KEY
            value: "/etc/etcd/secrets/etcd.key"
          - name: STSENTINEL_KEEPER_KUBE_LABEL_SELECTOR
            value: "stolon-cluster=kube-stolon,stolon-keeper=yes"
          - name: STSENTINEL_DEBUG
            value: "false"
          - name: STSENTINEL_KUBERNETES_NAMESPACE
            value: "default"
          - name: STSENTINEL_PORT
            value: "6431"
          - name: STSENTINEL_KEEPER_PORT
            value: "5431"
          - name: STSENTINEL_INITIAL_CLUSTER_CONFIG
            value: "/etc/stolon/cluster-config.json"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 150Mi
        ports:
          - containerPort: 6431
        volumeMounts:
          - mountPath: /etc/etcd/secrets
            name: etcd-secrets
      volumes:
        - name: etcd-secrets
          hostPath:
            path: /var/state
