apiVersion: v1
kind: ConfigMap
metadata:
  name: stolon-telegraf
  namespace: default
  labels:
    app: stolon
    component: telegraf
data:
  telegraf.conf: |+
    [global_tags]

    # Configuration for telegraf agent
    [agent]
      interval = "20s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = true
      hostname = ""
      omit_hostname = false


    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################
    [[outputs.influxdb]]
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"] # required
      database = "k8s" # required
      retention_policy = ""
      write_consistency = "any"
      timeout = "5s"
      username = "$INFLUXDB_USERNAME"
      password = "$INFLUXDB_PASSWORD"


    ###############################################################################
    #                            INPUT PLUGINS                                    #
    ###############################################################################
    [[inputs.postgresql]]
      ignored_databases = ["template0", "template1"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stolon-telegraf-node
  namespace: default
  labels:
    app: stolon
    component: telegraf-node
data:
  telegraf.conf: |+
    [global_tags]

    # Configuration for telegraf agent
    [agent]
      interval = "20s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = true
      hostname = ""
      omit_hostname = false


    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################
    [[outputs.influxdb]]
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"] # required
      database = "k8s" # required
      retention_policy = ""
      write_consistency = "any"
      timeout = "5s"
      username = "$INFLUXDB_USERNAME"
      password = "$INFLUXDB_PASSWORD"

    ###############################################################################
    #                            INPUT PLUGINS                                    #
    ###############################################################################
    [[inputs.postgresql_extensible]]
      address = "host=localhost user=$STOLON_USERNAME password=$STOLON_PASSWORD dbname=postgres sslmode=require"
      name_prefix = "postgresql_"
      [[inputs.postgresql_extensible.query]]
        sqlquery="SELECT * FROM pg_replication_lag()"
        version=901
        withdbname=false
        tagvalue=""
        measurement="lag"
      [[inputs.postgresql_extensible.query]]
        sqlquery="SELECT * FROM pg_stat_replication"
        version=901
        withdbname=false
        tagvalue="client_hostname,state,sent_location,write_location,flush_location,replay_location"
        measurement="replication_stats"
