---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-utils
  namespace: default
spec:
  selector:
    matchLabels:
      name: stolon-utils
      stolon-utils: "yes"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        name: stolon-utils
        namespace: default
        stolon-cluster: "kube-stolon"
        stolon-utils: "yes"
        component: utils
        product: stolon
    spec:
      serviceAccountName: stolon
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: utils
        image: stolon-telegraf:latest
        env:
          - name: STOLON_USERNAME
            value: "stolon"
          - name: STOLON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
          - name: INFLUXDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: username
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: password
        volumeMounts:
          - name: telegraf-config
            mountPath: /etc/telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: stolon-telegraf
